### ISSUE TITLE
LOC metric crashing when run against Scala project

### ISSUE THREAD

**Issue by selfdual-brain** [BasLeijdekkers/MetricsReloaded#57] opened 2019-05-28 14:50 UTC
my version of IDE is: IDEA 2018.3.4
Java 1.8.0_152 running on Ubuntu 18.04 LTS

stacktrace follows:

java.lang.NoSuchFieldError: SCALA_FILE_TYPE
	at com.sixrr.stockmetrics.projectMetrics.LinesOfScalaProjectMetric.createCalculator(LinesOfScalaProjectMetric.java:49)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:91)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by perlun** [comment] 2019-12-17 07:24
Seeing this as well with a multi-project setup that includes a Scala project. Very annoying.

**Comment by silvanheller** [comment] 2020-03-18 17:16
@BasLeijdekkers i think this was fixed in 51a7f70563070b762c65c59e27c36b38982c94f8 (this issue seems to be a duplicate of #42 ) but the fix was never pushed to the IntelliJ Marketplace (the latest version is from Sep 2016)

**Comment by BasLeijdekkers** [comment] 2020-04-18 15:52
I have finally released an update.

**Closed by BasLeijdekkers** 2020-04-18 15:52 UTC
